Revert "build: install multiple Python versions for autosynth runs (#641)"
This reverts commit 2a29860e484695a07aa8670f9e750bfeeb308a43.

It broke the build for all Python synth jobs.  Here's the log:

```
Downloading Python-3.7.7.tar.xz...
-> https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tar.xz
Installing Python-3.7.7...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems

BUILD FAILED (Ubuntu 14.04 using python-build 1.2.19-1-gece59ca8)
```

Source-Author: Jeffrey Rennie <rennie@google.com>
Source-Date: Wed Jun 24 10:39:14 2020 -0700
Source-Repo: googleapis/synthtool
Source-Sha: ce68c0e70d36c93ffcde96e9908fb4d94aa4f2e4
Source-Link: https://github.com/googleapis/synthtool/commit/ce68c0e70d36c93ffcde96e9908fb4d94aa4f2e4